### ISSUE TITLE
CondensedLightItalic font path error

### ISSUE THREAD

**Issue by danieltenefrancia** [dasrick/npm-font-open-sans#5]
Please fix the scss path for CondensedLightItalic 

`
@font-face {
  font-family: 'Open Sans Condensed';
  font-weight: 300;
  font-style: italic;
  src: url('#{$FontPathOpenSans}/CondensedLight/OpenSans-CondensedLightItalic.woff2') format('woff2'), url('#{$FontPathOpenSans}/CondensedLight/OpenSans-CondensedLightItalic.woff') format('woff'), url('#{$FontPathOpenSans}/CondensedLight/OpenSans-CondensedLightItalic.ttf') format('truetype'), url('#{$FontPathOpenSans}/CondensedLight/OpenSans-CondensedLightItalic.svg#OpenSansCondensedLightItalic') format('svg');
}
`
to 

`
@font-face {
  font-family: 'Open Sans Condensed';
  font-weight: 300;
  font-style: italic;
  src: url('#{$FontPathOpenSans}/CondensedLightItalic/OpenSans-CondensedLightItalic.woff2') format('woff2'), url('#{$FontPathOpenSans}/CondensedLightItalic/OpenSans-CondensedLightItalic.woff') format('woff'), url('#{$FontPathOpenSans}/CondensedLightItalic/OpenSans-CondensedLightItalic.ttf') format('truetype'), url('#{$FontPathOpenSans}/CondensedLightItalic/OpenSans-CondensedLightItalic.svg#OpenSansCondensedLightItalic') format('svg');
}
`

**Comment by dasrick** [comment]
Hi @danieltenefrancia,

this repository is about font "Open Sans" not about "Open Sans Condensed" ... so i think you choose the wrong repository ...

But i also provide a repository that includes the font "Open Sans Condensed": https://github.com/dasrick/npm-font-open-sans-condensed

cheers
dasrick

**Comment by danieltenefrancia** [comment]
Hi Dasrick,

Sorry for the mistake I was trying to report an issue on a different
repository,
I accidentally reported this issue in your repository.
Thanks for this,

Noong Mar, Peb 12, 2019 nang 5:30 PM, sinulat ni Enrico Hoffmann <
notifications@github.com> ang:
